# Generated by Django 5.2 on 2025-04-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='container_created_at',
            field=models.DateTimeField(blank=True, help_text='When the container was created', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='container_id',
            field=models.CharField(blank=True, help_text='Docker container ID', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='container_image',
            field=models.CharField(default='python:3.9-slim', help_text='Docker image used for the container', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='container_status',
            field=models.CharField(blank=True, help_text='Current status of the container', max_length=20, null=True),
        ),
    ]
