# Generated by Django 5.2 on 2025-04-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_project_container_created_at_project_container_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='container_image',
            field=models.CharField(default='python:latest', help_text='Docker image used for the container', max_length=100),
        ),
    ]
