# Generated by Django 5.2 on 2025-04-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_reasoningsession_reasoningstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_assistant_window_open',
            field=models.BooleanField(default=True, help_text='Whether the assistant window is open'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_reasoning_mode_on',
            field=models.BooleanField(default=False, help_text='Whether reasoning mode is enabled'),
        ),
    ]
