# Generated by Django 5.2 on 2025-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_is_assistant_window_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='web_server_internal_port',
            field=models.IntegerField(default=8000, help_text='Internal container port for web server'),
        ),
        migrations.AddField(
            model_name='project',
            name='web_server_path',
            field=models.CharField(default='/', help_text='Path to append to URL for web server preview', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='web_server_port',
            field=models.IntegerField(blank=True, help_text='Port for web server preview', null=True),
        ),
    ]
