# Generated by Django 5.2 on 2025-04-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_project_web_server_internal_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chat_panel_width',
            field=models.IntegerField(default=350, help_text='Width of the chat panel in pixels'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terminal_height',
            field=models.IntegerField(default=150, help_text='Height of the terminal panel in pixels'),
        ),
    ]
